app/app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError,TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo

from ..models import Employee


class RegistrationForm(FlaskForm):
    """
    Form for users to create new account
    """
    title = StringField('제목', validators=[DataRequired()])
    body  = TextAreaField('내용',  render_kw={"rows": 10, "cols": 1},validators=[DataRequired()])
    submit = SubmitField('Create')

    # def validate_email(self, field):
    #     if Employee.query.filter_by(email=field.data).first():
    #         raise ValidationError('Email is already in use.')

    # def validate_username(self, field):
    #     if Employee.query.filter_by(username=field.data).first():
    #         raise ValidationError('Username is already in use.')

app/app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views
#from . import openviews

app/app/blog/views.py
from flask import render_template, abort,flash,redirect,url_for,request
from flask_login import login_required,current_user
from datetime import datetime
from sqlalchemy import outerjoin

from . import blog
from ..models import Post,Employee
from .forms import RegistrationForm
from .. import db
from flask import current_app
# from config import POSTS_PER_PAGE

@blog.route('/blog/blogs')
def blogs():
    # posts = Post.query.order_by(Post.id.desc()).all()
    POSTS_PER_PAGE= current_app.config['POSTS_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    # posts = Post.query.order_by(Post.id.desc()).paginate(
    #     page, POSTS_PER_PAGE, False)
    
    #outer join을 하여 query()에서 Post,Employee컬럼을 추출 : username을 가져옴
    posts=db.session.query(Post.author_id,Post.title,Post.body,Post.created,Post.id,Employee.username).\
            outerjoin(Employee, Post.author_id == Employee.id).order_by(Post.id.desc()).\
            paginate(page, POSTS_PER_PAGE, False)
    # next_url = url_for('blog.blogs', page=posts.next_num) \
    #     if posts.has_next else None
    # prev_url = url_for('blog.blogs', page=posts.prev_num) \
    #     if posts.has_prev else None        
    # next_num= str(posts.next_num) + 'page'
    # prev_num= str(posts.prev_num) + 'page'
    # return render_template('blog/index.html', posts=posts.items, next_url=next_url,
    #                        prev_url=prev_url,next_num=next_num,prev_num=prev_num)
    return render_template('blog/index.html', posts=posts)


@blog.route('/blog/create', methods=('GET', 'POST'))
@login_required
def create():
    usern=current_user.username
    userid=current_user.id
    print('userid=',userid)
    now=datetime.now()
    form = RegistrationForm()
    if form.validate_on_submit():
        posts = Post(author_id=userid,
                            created=now,
                            title=form.title.data,
                            body=form.body.data)

        # add cars to the database
        db.session.add(posts)
        db.session.commit()

        flash('You have successfully registered blogs!!.')
        # redirect to the login page
        return redirect(url_for('blog.blogs'))

    # load registration template
    return render_template('blog/create.html', form=form, title='Register blog')

def get_post(id, check_author=True):
    post = get_db().execute(
        'SELECT p.id, title, body, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if post is None:
        abort(404, "Post id {0} doesn't exist.".format(id))

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post


@blog.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = Post.query.get_or_404(id)  #from table
    form = RegistrationForm(obj=post) #if not 404
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        error = None
        if not post.title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db.session.commit()
            flash('You have successfully edited the blogs.')
            return redirect(url_for('blog.blogs'))

    return render_template('blog/create.html', form=form, title='Update blog')

@blog.route('/<int:id>/detail', methods=('GET', 'POST'))
@login_required
def detail(id):
    post = Post.query.get_or_404(id)  #from table
    return render_template('blog/detail.html', post=post, title='Blog detials')

@blog.route('/<int:id>', methods=('POST','GET'))
@login_required
def delete(id):
    post = Post.query.get_or_404(id) 
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('blog.blogs'))

app/app/templates/blog/create.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %} {{title}} {% endblock %}
{% block body %}
<div class="content-section">
    <div class="center">
      <h1> {{title}} </h1>
      <br>
         {{ wtf.quick_form(form) }}
    </div>
  </div>
{% endblock %}

app/app/templates/blog/detail.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %} {{title}} {% endblock %}

{% block body %}
   <div class="content-section">
    <div class="container">
        <br>
        <div class="input-group">
            <span class="input-group-addon">Title</span>
            <input class="form-control" type="text" id="title" style="background-color: #F5FFFA;" value="{{ post['title'] }}" readonly>
        </div>
        <br>
        <div class="form-group">
            <textarea class="form-control" rows="20" id="body" style="background-color: #FFFFFF;" readonly> {{ post['body'] }}</textarea>
          </div>        
      </div>
    </div>
   </div>
{% endblock %}

app/app/templates/blog/index.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Blog{% endblock %}
{% block body %}
<div class="content-section">
  <h4> --- Glad Blogs ---</h4>
    <div class="outer">
       <div class="center">     
        {{ utils.flashed_messages() }}     
        {% for post in posts.items %}
          <article class="post">
           <div class="panel panel-default">  
            <div class="panel-heading">
              <div>
                <div style="float:left">{{ post['title'] }}</div>
                <div class="about" style="float:right">by {{ post['username'] }} / {{ post['created'].strftime('%Y-%m-%d') }}</div>
              </div>
            {% if current_user.id == post['author_id'] %}
              <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
              <a class="action" href="{{ url_for('blog.delete', id=post['id']) }}">Del</a>
            {% else %}
              <br>
            {% endif %}
            </div>
            <div class="panel-body">
              <a class="action" href="{{ url_for('blog.detail',id=post['id']) }}"> 
                {% set counter  = 0 %}
                {% for para in post['body'].split('\n')  %}
                   {% if (counter+loop.index0 < 2) %} 
                      {{para}} <br>
                   {% else %}
                      {% if ((counter+loop.index0 == 2)) %}
                        &nbsp; more . . . . . .
                      {% else %} 
                      {% endif %}
                   {% endif %}
                {% endfor %}
              </a>
            </div>
          </div>
         </article>
         {% if not loop.last %}
         {% endif %}
       {% endfor %}

       <!-- {% if prev_url %}
       <a href="{{ prev_url }}">{{prev_num}}</a>
       {% endif %}
       {% if next_url %}
       <a href="{{ next_url }}">{{next_num}}</a>
       {% endif %} -->
       <div style="text-align: center">
        <h5>
       {% for  page in posts.iter_pages(left_edge=3,right_edge=3,left_current=3,right_current=3) %}
         {% if page %}
            <a href="{{ url_for('blog.blogs',page=page) }}">{{page}}</a>
         {% else %}
            ...
         {% endif %}
       {% endfor %}
        </h5>
       </div>

      </div>
  </div>
</div>
{% endblock %}

app/app/templates/blog/openindex.html
{% extends "base.html" %}
{% block title %}
Blog Posts
{% endblock title %}

{% block main %}
    {% if alert %}
        <div class="alert alert-{{alert.type}}">
            <strong>{{ alert.type }}</strong> {{ alert.message }}
        </div>
    {% endif %}

    {% if meta.is_user_blogger %}
        <div class="pull-right">
            <a href="{{ url_for('blogging.editor') }}" id="new">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;New
            </a>
        </div>
    {% endif %}

    {% for post in posts %}
        <a href="{{ post.url }}">
            <h1>{{ post.title }}</h1>
        </a>
        <p>Posted by <a href="{{ url_for('blogging.posts_by_author', user_id=post.user_id)}}"><em>{{post.user_name}}</em></a>
        on {{post.post_date.strftime('%d %b, %Y')}}</p>

        <!-- post tags-->
        {% if post.tags %}
            <span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;
            {% for tag in post.tags %}
                <span class="label">
                    <a href="{{ url_for('blogging.posts_by_tag', tag=tag.lower(), count=10, offset=0) }}">
                    {{ tag }}
                    </a>
                </span>&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endif %}
        <hr>
    {% endfor %}
    {% if ((meta)  and (meta.max_pages>1)) %}
        <div class="row">
            <div class="col-md-12">
                <ul class="pager">
                    {% if meta.pagination.prev_page %}
                        <li><a href="{{meta.pagination.prev_page}}">&laquo; Prev</a></li>
                    {% else %}
                        <li class="disabled"><a href="">&laquo; Prev</a></li>
                    {% endif %}
                    {% if meta.pagination.next_page %}
                        <li><a href="{{meta.pagination.next_page}}">Next &raquo;</a></li>
                    {% else %}
                        <li class="disabled"><a href="">Next &raquo;</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    {% endif %}
{% endblock main %}

app/app/templates/blog/update.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Blog Update{% endblock %}

{% block body %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}