app/app/cars/__init__.py
from flask import Blueprint

cars = Blueprint('cars', __name__)

from . import views

app/app/cars/views.py
from flask import flash, redirect, render_template, url_for,send_from_directory,request,send_file,jsonify
from flask_login import login_required, current_user
from sqlalchemy import desc
from werkzeug.utils import secure_filename
import os
from datetime import datetime

from . import cars
from .forms import RegistrationForm
from .. import db
from ..models import Cars
from ..models import Employee
from flask import current_app


@cars.route('/cars/register', methods=['GET', 'POST'])
@login_required
def register():
    """
    Handle requests to the /register route
    Add an employee to the database through the registration form
    """
    add_cars=True
    usern=current_user.username
    form = RegistrationForm()
    if form.validate_on_submit():
        #from Forms to columns
        cars=Cars()
        SetCars(cars,form,'n')       
        cars.status = '요청'          
        # add cars to the database
        files = request.files.getlist('file')
        if files:
           filenm=uploads(files,cars.customer_name)
           cars.filename=filenm
           # print('files = ', cars.filename)
        db.session.add(cars)
        db.session.commit()

        flash('You have successfully registered! cars!!.')
        # redirect to the page
        return redirect(url_for('cars.carslist'))

    # load registration template
    form.cov_object.default = '5천'   #초기값
    form.cov_self.default = '자신3'
    form.process()    #
    return render_template('cars/register.html', form=form, title='Register cars',add_cars=add_cars)


@cars.route('/cars/carslist', methods=['GET', 'POST'])
@login_required
def carslist():
    """
    List all cars
    """
    # CARS_PER_PAGE=10
    CARS_PER_PAGE= current_app.config['CARS_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    ##username으로 employee 테이블을 읽어 admin이 아닌 경우 본인건만 select
    usern=current_user.username
    employee = Employee.query.filter_by(username=usern).first()
    if employee.is_admin:
        cars = Cars.query.order_by(Cars.id.desc()).paginate(
            page, CARS_PER_PAGE, False)
    else: 
        cars = Cars.query.filter_by(fc_id=usern).order_by(Cars.id.desc()).paginate(
            page, CARS_PER_PAGE, False)

    ##next,prev url은 미사용 --참고용으로 남겨놓음
    next_url = url_for('cars.carslist', page=cars.next_num) \
        if cars.has_next else None
    prev_url = url_for('cars.carslist', page=cars.prev_num) \
        if cars.has_prev else None        
    next_num= str(cars.next_num) + 'page'
    prev_num= str(cars.prev_num) + 'page'

    # cars = Cars.query.order_by(Cars.id.desc()).all()

    return render_template('cars/carslist.html',
                           cars=cars, title="carslist",next_url=next_url,
                           prev_url=prev_url,next_num=next_num,prev_num=prev_num)

@cars.route('/cars/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_car(id):
    """
    Edit a car
    """
    # check_admin()

    add_cars = False

    car = Cars.query.get_or_404(id)  #from table
    form = RegistrationForm(obj=car) #if not 404
    if form.validate_on_submit():
        SetCars(car,form,'u')
        car.updated = datetime.now()
        files = request.files.getlist('file')
        if files:
           filenm= uploads(files,car.customer_name)     
           car.filename=filenm
           #print('files = ', car.filename)
        db.session.commit()
        flash('You have successfully edited the cars.')

        # redirect to the departments page
        return redirect(url_for('cars.carslist'))
    filenm=''
    if car.filename:
       filenm = 'attached img= ' + car.filename
    return render_template('cars/register.html', action="Edit",
                           add_cars=add_cars, form=form,
                           title="Edit car",filename=filenm)

@cars.route('/cars/update_car', methods=['GET', 'POST'])
def update_car():
    data={}  #empty dict
    data['id'] = request.args.get('id', 0, type=int)
    data['car_rcompany'] = request.args.get('rst_company', 0, type=str)
    data['car_rdate'] = request.args.get('rst_date', 0, type=str)
    data['status'] = request.args.get('status', 0, type=str)
    car = Cars.query.get_or_404(data['id']) 
    if car: 
        if data['car_rcompany']:
           car.rst_company=data['car_rcompany']
        else: car.rst_company=None
        if data['car_rdate']:
           car.rst_date = data['car_rdate']
        else: car.rst_date=None           
        car.status = data['status']
        car.updated = datetime.now()
        db.session.commit()
    # print('upd============',data['id'],data['status'],data['car_rcompany'])
    # return jsonify(data)  #browser로 return
    return data  #browser로 return

def SetCars(car,form,gb):
        car.company = form.company.data
        car.customer_name = form.customer_name.data
        car.customer_id = form.customer_id.data
        car.customer_telno = form.customer_telno.data
        car.customer_address = form.customer_address.data
        car.customer_job = form.customer_job.data
        car.customer_eq = form.customer_eq.data
        car.owner_name = form.owner_name.data
        car.owner_id = form.owner_id.data
        car.owner_telno = form.owner_telno.data
        car.owner_address = form.owner_address.data
        car.owner_job = form.owner_job.data

        car.car_no = form.car_no.data
        car.car_name = form.car_name.data
        car.car_code = form.car_code.data
        car.car_year = form.car_year.data
        car.car_acc = form.car_acc.data

        car.fc_id = current_user.username
        car.description = form.description.data.encode('utf8')

        car.age_limit=form.age_limit.data
        car.driver_limit=form.driver_limit.data
        car.driver_id=form.driver_id.data
        car.driver_name=form.driver_name.data        
        car.cov_mandatory=form.cov_mandatory.data        
        car.cov_person=form.cov_person.data        
        car.cov_object =form.cov_object.data        
        car.cov_self =form.cov_self.data        
        car.cov_car =form.cov_car.data        
        car.cov_noncover  =form.cov_noncover.data        
        car.spc_emergency   =form.spc_emergency.data        
        car.spc_blackbox    =form.spc_blackbox.data   
        car.spc_mileage     =form.spc_mileage.data  
        if gb=='n':
           car.created = datetime.now()
        car.exp_date = form.exp_date.data
        return car


@cars.route('/cars/filedown/<string:filename>', methods=['GET', 'POST'])
def download_file(filename):	
    # UPLOAD_FOLDER='../uploads/'
    UPLOAD_FOLDER= current_app.config['UPLOAD_FOLDER']
    files = filename.split(',')
    for filenm in files:
        filepath= os.path.join(UPLOAD_FOLDER, filenm)
       # send_file(filepath, as_attachment=True)  ##-파일 즉시 다운
        return send_from_directory(directory=UPLOAD_FOLDER, filename=filenm)	
    
def allowed_file(filename):
    # ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
    ALLOWED_EXTENSIONS= current_app.config['ALLOWED_EXTENSIONS']
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def uploads(files,key):
    UPLOAD_FOLDER= current_app.config['UPLOAD_FOLDER']
    # file = request.files.getlist('file')
    result_nm=''
    if files: 
       for file in files:
           if allowed_file(file.filename):
#              filename = secure_filename(key+'_'+file.filename)
              filename = key+'_'+file.filename 
            #   UPLOAD_FOLDER='../uploads/'
              filesv= os.path.join(UPLOAD_FOLDER, filename)
              file.save(filesv)
              if result_nm == '':
                  result_nm = filename
              else: 
                  result_nm += ','+ filename
        #return filename   #파일명만 저장
       return result_nm

@cars.route('/cars/fileupload', methods=['GET', 'POST'])
@login_required
def fileupload():	
    if request.method == 'POST':	
        f=request.files['file']	
        print('--------upload 11-',f.filename)	
        a=f.filename	
       # a = a.decode('cp949').encode('utf-8')	
        print('--------upload 11-1--',a)	
        f.save('./files/'+ secure_filename(a))	
        return redirect(url_for('blog.index'))	
       #return 'succ load'	
   	
    return render_template('uploads/fileupload.html')	

app/cars/__init__.py
from flask import Blueprint

cars = Blueprint('cars', __name__)

from . import views

app/cars/views.py
from flask import flash, redirect, render_template, url_for,send_from_directory,request,send_file,jsonify
from flask_login import login_required, current_user
from sqlalchemy import desc
from werkzeug.utils import secure_filename
import os
from datetime import datetime

from . import cars
from .forms import RegistrationForm
from .. import db
from ..models import Cars
from ..models import Employee,GladFc
from flask import current_app


@cars.route('/cars/register', methods=['GET', 'POST'])
@login_required
def register():
    """
    Handle requests to the /register route
    Add an employee to the database through the registration form
    """
    add_cars=True
    usern=current_user.username
    form = RegistrationForm()
    if form.validate_on_submit():
        #처리자 지점값 설정
        usern=current_user.username
        employee = Employee.query.filter_by(username=usern).first()
        brh_name= getBrhName(employee.glad_id)

        #from Forms to columns
        cars=Cars()
        SetCars(cars,form,'n',brh_name)       
        cars.status = '요청'          
        # add cars to the database
        files = request.files.getlist('file')
        if files:
           filenm=uploads(files,cars.customer_name)
           cars.filename=filenm
           # print('files = ', cars.filename)
        db.session.add(cars)
        db.session.commit()

        # flash('You have successfully registered! cars!!.')
        # redirect to the page
        return redirect(url_for('cars.carslist'))

    # load registration template
    form.cov_object.default = '5천'   #초기값
    form.cov_self.default = '자신3'
    form.process()    #
    return render_template('cars/register.html', form=form, title='Register cars',add_cars=add_cars)

def getBrhName(glad_id):
    if glad_id==None:
        return 'None'
    if glad_id.startswith('MPK'):
       gladfc = GladFc.query.filter_by(glad_id=glad_id).first()
       brh_name= gladfc.glad_brh
    else: 
       brh_name = '본부'
    return brh_name 

@cars.route('/cars/carslist', methods=['GET', 'POST'])
@login_required
def carslist():
    """
    List all cars
    """
    # CARS_PER_PAGE=10
    CARS_PER_PAGE= current_app.config['CARS_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    ##username으로 employee 테이블을 읽어 admin이 아닌 경우 본인건만 select
    usern=current_user.username
    employee = Employee.query.filter_by(username=usern).first()
    if employee.is_admin:  #admin는 all 권한
        cars = Cars.query.order_by(Cars.id.desc()).paginate(
            page, CARS_PER_PAGE, False)
    elif employee.role_id==1:  #지점장 or 실장은 자기지점만      
        brh_name= getBrhName(employee.glad_id)     
        cars = Cars.query.filter_by(brh_name=brh_name).order_by(Cars.id.desc()).paginate(
            page, CARS_PER_PAGE, False)
    else: 
        cars = Cars.query.filter_by(fc_id=usern).order_by(Cars.id.desc()).paginate(
            page, CARS_PER_PAGE, False)

    ##next,prev url은 미사용 --참고용으로 남겨놓음
    next_url = url_for('cars.carslist', page=cars.next_num) \
        if cars.has_next else None
    prev_url = url_for('cars.carslist', page=cars.prev_num) \
        if cars.has_prev else None        
    next_num= str(cars.next_num) + 'page'
    prev_num= str(cars.prev_num) + 'page'

    # cars = Cars.query.order_by(Cars.id.desc()).all()

    return render_template('cars/carslist.html',
                           cars=cars, title="carslist",next_url=next_url,
                           prev_url=prev_url,next_num=next_num,prev_num=prev_num)

@cars.route('/cars/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_car(id):
    """
    Edit a car
    """
    # check_admin()

    add_cars = False

    car = Cars.query.get_or_404(id)  #from table
    form = RegistrationForm(obj=car) #if not 404
    if form.validate_on_submit():
        SetCars(car,form,'u',"")
        car.updated = datetime.now()
        files = request.files.getlist('file')
        if files:
           filenm= uploads(files,car.customer_name)     
           car.filename=filenm
           #print('files = ', car.filename)
        db.session.commit()
        # flash('You have successfully edited the cars.')

        # redirect to the departments page
        return redirect(url_for('cars.carslist'))
    filenm=''
    if car.filename:
       filenm = 'attached img= ' + car.filename
    return render_template('cars/register.html', action="Edit",
                           add_cars=add_cars, form=form,
                           title="Edit car",filename=filenm)

@cars.route('/cars/update_car', methods=['GET', 'POST'])
def update_car():
    data={}  #empty dict
    data['id'] = request.args.get('id', 0, type=int)
    data['car_rcompany'] = request.args.get('rst_company', 0, type=str)
    data['car_rdate'] = request.args.get('rst_date', 0, type=str)
    data['status'] = request.args.get('status', 0, type=str)
    data['rt_cause'] = request.args.get('rt_cause', 0, type=str)
    # print(data['rt_cause'])
    car = Cars.query.get_or_404(data['id']) 
    if car: 
        if data['car_rcompany']:
           car.rst_company=data['car_rcompany']
        else: car.rst_company=None
        if data['car_rdate']:
           car.rst_date = data['car_rdate']
        else: car.rst_date=None           
        car.status = data['status']
        car.rt_cause = data['rt_cause']
        car.updated = datetime.now()
        db.session.commit()
    # print('upd============',data['id'],data['status'],data['car_rcompany'])
    # return jsonify(data)  #browser로 return
    return data  #browser로 return

def SetCars(car,form,gb,brh_name):
        car.company = form.company.data
        car.customer_name = form.customer_name.data
        car.customer_id = form.customer_id.data
        car.customer_telno = form.customer_telno.data
        car.customer_address = form.customer_address.data
        car.customer_job = form.customer_job.data
        car.customer_eq = form.customer_eq.data
        car.owner_name = form.owner_name.data
        car.owner_id = form.owner_id.data
        car.owner_telno = form.owner_telno.data
        car.owner_address = form.owner_address.data
        car.owner_job = form.owner_job.data

        car.car_no = form.car_no.data
        car.car_name = form.car_name.data
        car.car_code = form.car_code.data
        car.car_year = form.car_year.data
        car.car_acc = form.car_acc.data

        car.fc_id = form.fc_id.data
        car.proc_id = current_user.username
        car.description = form.description.data.encode('utf8')

        car.age_limit=form.age_limit.data
        car.driver_limit=form.driver_limit.data
        car.driver_id=form.driver_id.data
        car.driver_name=form.driver_name.data        
        car.cov_mandatory=form.cov_mandatory.data        
        car.cov_person=form.cov_person.data        
        car.cov_object =form.cov_object.data        
        car.cov_self =form.cov_self.data        
        car.cov_car =form.cov_car.data        
        car.cov_noncover  =form.cov_noncover.data        
        car.spc_emergency   =form.spc_emergency.data        
        car.spc_blackbox    =form.spc_blackbox.data   
        car.spc_mileage     =form.spc_mileage.data
        if gb=='n':
           car.created = datetime.now()
           car.brh_name= brh_name
        car.exp_date = form.exp_date.data
        return car


@cars.route('/cars/filedown/<string:filename>', methods=['GET', 'POST'])
def download_file(filename):	
    # UPLOAD_FOLDER='../uploads/'
    UPLOAD_FOLDER= current_app.config['UPLOAD_FOLDER']
    # UPLOAD_FOLDER= '../'+UPLOAD_FOLDER
    files = filename.split(',')
    for filenm in files:
        filepath= os.path.join(UPLOAD_FOLDER, filenm)
       # send_file(filepath, as_attachment=True)  ##-파일 즉시 다운
        print(UPLOAD_FOLDER,filenm)
        return send_from_directory(directory=UPLOAD_FOLDER, filename=filenm)	
    
def allowed_file(filename):
    # ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
    ALLOWED_EXTENSIONS= current_app.config['ALLOWED_EXTENSIONS']
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def uploads(files,key):
    UPLOAD_FOLDER= current_app.config['UPLOAD_FOLDER']
    # file = request.files.getlist('file')
    result_nm=''
    if files: 
       for file in files:
           if allowed_file(file.filename):
#              filename = secure_filename(key+'_'+file.filename)
              filename = key+'_'+file.filename 
              filesv= os.path.join(UPLOAD_FOLDER, filename)
              file.save(filesv)
              if result_nm == '':
                  result_nm = filename
              else: 
                  result_nm += ','+ filename
        #return filename   #파일명만 저장
       return result_nm

@cars.route('/cars/fileupload', methods=['GET', 'POST'])
@login_required
def fileupload():	
    if request.method == 'POST':	
        f=request.files['file']	
        print('--------upload 11-',f.filename)	
        a=f.filename	
       # a = a.decode('cp949').encode('utf-8')	
        print('--------upload 11-1--',a)	
        f.save('./files/'+ secure_filename(a))	
        return redirect(url_for('blog.index'))	
       #return 'succ load'	
   	
    return render_template('uploads/fileupload.html')	

app/templates/cars/carslist - 복사본.html
<!-- app/templates/cars/carslist.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}carsList{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <h3 style="text-align:center;">견적 리스트</h3>
        {% if cars %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered" id="tb" name="tb">
              <thead>
                <tr>
                  <th width="10%"> 신청일 </th>
                  <th width="10%"> 신청자 </th>
                  <th width="15%"> 계약자 </th>
                  <th width="15%"> 피보험자 </th>
                  <th width="15%"> 연락처 </th>
                  <th width="15%"> 차량번호 </th>
                  <th width="10%"> 현보험사 </th>
                  <th width="5%"> action </th>
                  <th width="5%"> docs </th>
                </tr>
              </thead>
              <tbody>
              {% set counter  = 0 %}
              {% for car in cars %}
                <tr>
                  {% if car.created %}
                  <td> {{ car.created.strftime('%y-%m-%d') }} </td>
                  {% else %}
                  <td>  </td>
                  {% endif %}
                  <td> {{ car.customer_id }} </td>
                  <td> <a href="{{ url_for('.edit_car', id=car.id) }}">
                       <i class="fa fa-pencil"> </i> {{ car.customer_name }} 
                       </a>
                  </td>
                  <td> {{ car.owner_name }} </td>
                  <td> {{ car.customer_telno }} </td>
                  <td> {{ car.car_no }} </td>
                  <td> {{ car.company }} </td>
                  <td>
                    <!-- 모달을 열기 위한 버튼 -->	
                    <a data-toggle="modal" href="#modalBox" data-id={{car.id}}  data-cnt={{counter+loop.index0}} data-company={{car.rst_company}} data-sdate={{car.rst_date}} data-status={{car.status}}>결과</a>
                    <!-- <button class="btn btn-default btn-sm pull-right" id="rest1" data-value1={{car.id}} data-value2={{counter+loop.index0}} data-value3={{car.rst_company}} data-value4={{car.rst_date}} data-value5={{car.status}}> 결과</button> -->
                    <!-- <button class="btn btn-default btn-sm pull-right" id="rest1{{counter+loop.index0}}" data_value1={{car.id}} data_value2={{counter+loop.index0}} data_value3={{car.rst_company}} data_value4={{car.rst_date}} data_value5={{car.status}} onclick="javascript:clickTrEvent(this)""> 결과</button> -->
                    <!-- <button class="btn btn-default btn-sm pull-right" id="rest1"  onclick="javascript:clickTrEvent(this,{{car.id}}, {{counter+loop.index0}}, {{car.rst_company}}, {{car.rst_date}}, {{car.status}})"> 결과</button>  -->
                  </td>
                  <td>
                    {% if car.filename %}
                       {% for files in car.filename.split(',') %}
                         <a href="{{ url_for('cars.download_file', filename=files) }}">                  
                           <i class="fa fa-pencil"></i> View 
                         </a>
                       {% endfor %}
                    {% else %}
                      <i class="fa fa-pencil"></i>  
                    {% endif %}
                  </td> 
                </tr>
               
              {% endfor %}
              </tbody>
            </table>
            {% if prev_url %}
               <a href="{{ prev_url }}">{{prev_num}}</a>
            {% endif %}
            {% if next_url %}
               <a href="{{ next_url }}">{{next_num}}</a>
            {% endif %}
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No cars have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('cars.register') }}" class="btn btn-info">
            <i class="fa fa-plus"></i>
            견적의뢰
          </a>
          <input name="hiddenCounter" type="hidden" id="hiddenCounter">
          <input name="hiddenId" type="hidden" id="hiddenId">
          <input name="hiddenCompany" type="hidden" id="hiddenCompany">
          <input name="hiddenDate" type="hidden" id="hiddenDate">
          <input name="hiddenStatus" type="hidden" id="hiddenStatus">
        </div>
      </div>
    </div>
  </div>
</div>
	


<!-- 모달 영역 -->	
<div id="modalBox" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">	
  <div class="modal-dialog" role="document">	
    <div class="modal-content">	
      <div class="modal-header">	
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>	
        <h4 class="modal-title" id="myModalLabel">처리결과</h4>	
      </div>	
      <div class="modal-body">
        <label class="radio-inline"><input type="radio" name="optradio" value="01">요청</label>
        <label class="radio-inline"><input type="radio" name="optradio" value="02">처리중</label>
        <label class="radio-inline"><input type="radio" name="optradio" value="03">완료</label>
	    <br> <br>
        <div class="row">	     
          <div class="col-sm-2">가입사</div>
          <div class="col-sm-4">
            <input name="rst_company" id="rst_company" type="text" >
          </div>
          <div class="col-sm-2">가입일</div>
          <div class="col-sm-4">
            <input name="rst_date" id="rst_date"  type="text" size="8">
          </div>
        </div>
      </div>
      <div class="modal-footer">	
        <div class="row">
           <!--<button type="button" class="btn btn-primary">처리</button>	-->
          <div class="col-sm-offset-4 col-sm-2">
             <input type="submit" class="btn btn-primary" value="처리" id="procModalBtn">	
          </div> 
          <div class="col-sm-2">
            <button type="button" class="btn btn-default" id="closeModalBtn">취소</button>	
          </div>
        </div>
      </div>	
    </div>	
  </div>	
</div>	

<script type=text/javascript>	
 $(document).ready(function() {
  $('#rest1').on('click',function(){
    alert("Your values are :"+ $(this).data("value1")+","+$(this).data("value2")+","+$(this).data("value3"));
    var id= $(this).data("value1");
    var i= $(this).data("value2");
    var company= $(this).data("value3");
    var sdate= $(this).data("value4");
    var status= $(this).data("value5");
    // This populates a hidden input field (you will need to create somewhere in the page) with ID
    $("#hiddenId").val(id);
    $("#hiddenCounter").val(i);
    $("#hiddenCompany").val(company);
    $("#hiddenDate").val(sdate);
    $("#hiddenStatus").val(status);
   // Shows your modal
    $("#modalBox").modal("show");
    });
  });

  var id,i,sdate,company,status;
  function clickTrEvent(trObj,id) {
    // alert(company);
			alert(company);
	};

  // 모달 버튼에 이벤트를 건다.	
  $('#openModalBtn').on('click', function(){	
    $('#modalBox').modal('show');	
	  // console.log("click open");	
  });	
  // 모달 안의 처리 버튼에 이벤트를 건다.	
  //함수사용법-> getJSON(url, arguments, return객체) 
  $('#procModalBtn').on('click', function(){
     alert($(":input:radio[name=optradio]:checked").val());  //radio값 가져오기
     $.getJSON('/cars/update_car', {
        id: $('input[name="hiddenId"]').val(),
        rst_company: $('input[name="rst_company"]').val(),
        rst_date: $('input[name="rst_date"]').val(),
        staus: $(":input:radio[name=optradio]:checked").val()
        }, function(data) {  
          console.log(data);	                    
          // view에서 리턴받은 후 처리
          // var tr = button.parent().parent().eq(i);
          // alert($("#hiddenCounter").val());
          // $("#result").text(data.car_rcompany);
         });
         $('#modalBox').modal('hide');
        var c = $("#hiddenCounter").val();   //클릭한 row
        var tr_length = $('#tb tr').length-1;//맨위 테이블 row제외
        var tab_td = $('#tb td');//tb 테이블의 td들 불러오기
        var textDot = "..."; //말 줄임표
        var tds= $('#tb th').length;      //tr당 td수=헤더수
        for (var i = 0; i < tr_length; i++) { 
           // var td1 = tab_td.eq(i).text();
           // if(td1.length>20){                 //35글자가 넘으면
           //     $("#tb td:eq("+i+")").html(td1.substr(0,20)+textDot);
           if (i == c) {  //클릭한 이면 7번째 td값 변경
              var idx = i*tds + 7;   
              $("#tb td:eq("+idx+")").html($('input[name="rst_company"]').val());
              //$("#tb td:eq("+idx+")")[0].innerText=$('input[name="rst_company"]').val();
           }
         }
         
       
  });	

  // 모달 안의 취소 버튼에 이벤트를 건다.	
  $('#closeModalBtn').on('click', function(){	
    $('#modalBox').modal('hide');	
	// console.log("click close");	
  });	
  //모달 열릴때
  $('#modalBox').on('show.bs.modal', function (e) {	 
     var button= $(e.relatedTarget); 
     var id = button.data('id'); 
     var cnt = button.data('cnt'); 
     var company = button.data('company'); 
     var sdate = button.data('sdate'); 
     var status = button.data('status'); 
     alert(id);
     $(this).find('#rst_company').val(company);
     $(this).find('#rst_date').val(sdate);
     $(this).find('input:radio[name=optradio]:input[value='+status+']').attr("checked", true);  //radio box값 설정
  });	
  //모달 열린후
  $('#modalBox').on('shown.bs.modal', function (e) {	
    // console.log("shown.bs.modal");	
  });	
  //모달 닫힐때
  $('#modalBox').on('hide.bs.modal', function (e) {	
    // console.log("hide.bs.modal");	
  });	
  //모달 닫힌후
  $('#modalBox').on('hidden.bs.modal', function (e) {	
    // console.log("hidden.bs.modal");	
  });	

</script>

{% endblock %}

app/templates/cars/register - 복사본.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_cars %}
        Add cars
    {% else %}
        Edit cars
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="center">
       {% if add_cars %}
          <h1>견적 신청</h1>
       {% else %}
          <h1>견적 수정</h1>
       {% endif %}
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}