app/app/sales/__init__.py
from flask import Blueprint

sales = Blueprint('sales', __name__)

from . import views

app/app/sales/views.py
from flask import flash, redirect, render_template, url_for,request,send_file,json,jsonify
from flask_login import login_required, current_user
from sqlalchemy import desc
from werkzeug.utils import secure_filename
import os
from datetime import datetime,date

from .. import MyDateUtil as MyU  #자체 유틸리티 클래스 로딩
from .. import GladUtil as glad

from .. import db
from . import sales
import pandas as pd
from flask import current_app
from sqlalchemy import create_engine
import sys
import pymysql

EXCEL_EXTENSIONS=['xlsx','xsl']

getDT = MyU.getDateUtil()
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in EXCEL_EXTENSIONS

def getdata(by):
    fl='d:/글로벌/실적분석/곰스_2004.xlsx'
    df= pd.read_excel(fl,header=0)
    df['계약일자']=pd.to_datetime(df.계약일자,format='%Y-%m-%d')

    import datetime
    fr=pd.to_datetime('2020-04-01',format='%Y-%m-%d')
    to=pd.to_datetime('2020-04-30',format='%Y-%m-%d')
    cond2= (df.계약일자 >= fr) & (df.계약일자 <= to)
    if by=='brh':
        df2=pd.DataFrame(df[cond2].groupby(['지점'])['초회보험료'].agg('sum'))
    elif by=='day':
        df2=pd.DataFrame(df[cond2].groupby(['계약일자'])['초회보험료'].agg('sum'))
    else: return 'err'

    df2=df2.reset_index()
    return df2

labels = [
    'JAN', 'FEB', 'MAR', 'APR',
    'MAY', 'JUN', 'JUL', 'AUG',
    'SEP', 'OCT', 'NOV', 'DEC'
]

values = [
    967.67, 1190.89, 1079.75, 1349.19,
    2328.91, 2504.28, 2873.83, 4764.87,
    4349.29, 6458.30, 9907, 16297
]

colors = [
    "#F7464A", "#46BFBD", "#FDB45C", "#FEDCBA",
    "#ABCDEF", "#DDDDDD", "#ABCABC", "#4169E1",
    "#C71585", "#FF4500", "#FEDCBA", "#46BFBD"]
    
def getConnector():
    con_db = current_app.config['SQLALCHEMY_DATABASE_URI']
    con_db = con_db.rsplit('/')[len(con_db.rsplit('/'))-1]
    print('database ===== ' ,con_db)
    return pymysql.connect(host="localhost",user="glad",
             passwd="glad9",db=con_db)
    
def getSelects():
    results=[]
    db=getConnector()
    try:
        with db.cursor() as cursor:
            query="SELECT distinct year(계약일자),month(계약일자) FROM contracts order by 1 desc,2 desc ;"
            cursor.execute(query)
            records = cursor.fetchall()
 
        for row in records:
            results.append(str(row[0])+'.'+str(row[1]).zfill(2))
            # print('sql result----',row[0],row[1],results)
            
    except Exception as e:
        print("Error reading data from MySQL table", e)
    finally:
        db.close()
        return results    

def getDataframe(chk):
    results=[]
    db=getConnector()
    chk=chk.split('.')
    import datetime
    # print('param===',chk,int(chk[0]), int(chk[1]))
    d = datetime.date( int(chk[0]), int(chk[1]), 1)
    l_date= datetime.date(d.year+(d.month==12),(d.month+1 if d.month<12 else 1),1)-datetime.timedelta(1)
    
    try:
        with db.cursor(pymysql.cursors.DictCursor) as cursor:   
            query="SELECT * FROM contracts where 계약종류 in ('장기','생보') and 계약일자>='%s' and 계약일자 <= '%s' ;"%(d,l_date)
            print(query)
            cursor.execute(query)
            result = cursor.fetchall()
            result = pd.DataFrame(result)
    except Exception as e:
        print("Error reading data from MySQL table", e)
    finally:
        db.close()
        return result  

def dfProc(df):
    df.loc[:,'월']=df.계약일자.map(lambda x: x[:7]+'월')
    df.loc[:,'계약일자']=pd.to_datetime(df.계약일자,format='%Y-%m-%d')
    df.rename(columns={'납입주기(방법)':'납입방법'}, inplace=True)
    temp = df.loc[df['납입방법']=='년납','초회보험료'] / 12
    df.loc[df['납입방법']=='년납','초회보험료'] = temp
    del temp
    temp = df.loc[df['납입방법']=='일시납','초회보험료'] / 10
    df.loc[df.납입방법=='일시납','초회보험료'] = temp
    del temp

    df.loc[:,'최종상태변경일']=pd.to_datetime(df.최종상태변경일,format='%Y-%m-%d')
    df.loc[:,'말일']=pd.to_datetime(df.계약일자.map(getDT.get_lastday))
    df.loc[:,'월말계약상태']= df.계약상태
    df.loc[df.말일 < df.최종상태변경일,'월말계약상태']='정상'
    df=df[df.월말계약상태=='정상']  #계약월 기준인 경우 계약월말 정상건만 추출
    df=glad.BrhConv(df,'지점그룹')
    df.loc[:,'영업일차']=df.계약일자.map(getDT.get_workdaysMonth)
    return df


def dfMake(maxDay):
    월=list(range(0,maxDay))
    일차=list(range(1,maxDay+1))
    실적= [0]* maxDay
    누계= [0]* maxDay
    dfd=pd.DataFrame()
    dfd=pd.DataFrame({'월':월,'일차':일차,'실적':실적,'누계':누계})
    return dfd

def workDates(dt):
    wd1=date(dt.year,dt.month,1)
    wd2=getDT.get_lastday(wd1)
    return getDT.get_workdates(wd1,wd2)

@sales.route("/line_chart", methods=['GET', 'POST'])
@login_required
def line_chart():
    values=[]
    labels=[]
    legend=''
    title="실적추세"
    # getDT = MyU.getDateUtil()
    maxDay=0  #최대영업일수
    workDateList=[] #당월의 영업일 list

    if request.method == 'POST': # submit
        legend = 'sales'
        #checkboxs = request.form.getlist('checkboxs')
        checkboxs = request.form.getlist('chkYm[]')
        name = request.form.get('Types')
        print('from req= ',checkboxs,name)
        
        dfList=[pd.DataFrame()]*len(checkboxs)
        i=0
        for chk in checkboxs:
            df=getDataframe(chk)
            df=dfProc(df)
            df2=df.groupby(['월','영업일차'])['초회보험료'].agg('sum')
            df2=df2.reset_index()
            dfList[i]=df2
            # li=list(df2.초회보험료)
            # values.append(li)   
            # la=list(df2.영업일차)
            # labels.append(la)
            maxDay=max(maxDay, df2.영업일차.max()) 
            if i==0:  #당월의 영업일 목록
               workDateList=workDates(df.계약일자[0])
            #    print(len(workDateList), workDateList)
            i = i + 1

        maxDay += 1   
        workDateList2=[]
        for x in workDateList:
            workDateList2.append(x.strftime('%Y-%m-%d') )

        #영업일 리스트가 적은 경우
        i = maxDay - len(workDateList2)
        if i  > 0:
            for k in range(1,i):
                dt=workDateList2[len(workDateList2)-1]
                workDateList2.append(dt)

        dfThis=pd.DataFrame()
        #dflist loop
        for seq, dfRow in enumerate(dfList):
            df_Temp = pd.DataFrame(dfRow.groupby(['월','영업일차'])['초회보험료'].agg('sum')).reset_index()  #집계
            df_Temp['초회보험료']=round(df_Temp['초회보험료']/ 1000,0)
            df_Temp['csum'] = df_Temp.groupby(['월'])['초회보험료'].cumsum()  #누계생성
            dfd = dfMake(maxDay)
            dfd['월']=df_Temp.월[0]   #컬럼 초기화
            dfd['실적']=0
            dfd['누계']=0
            # print('df_temp',seq, df_Temp)
            for seq1, row in enumerate(df_Temp.iterrows()):    # groupby df를 dfSum에 복사
                # print('m=',maxDay,'s=',seq1, row[1])
                dfd.iloc[seq1]=[row[1][0],row[1][1],row[1][2],row[1][3]]

            dfd['누계']=  dfd.실적.expanding().sum()  #빈 row의 값을 채움
            if seq==0:
                dfThis=dfd
            li=list(dfd.누계)
            values.append(li)   
            # la=list(dfd.일차)
            la=workDateList2
            labels.append(la)

        #당월분 추가--막대그래프용
        values.append(list(dfThis.실적))
        labels.append(workDateList2)
        
        # return render_template('sales/line_chart.html', values=values, labels=labels, legend=legend,title=title)
        return jsonify({'resdata':json.dumps({'data':values, 'labels':labels,'checks':checkboxs})})
    
    # db에서 년월 조회
    results=getSelects()
    return render_template('sales/line_chart.html', title=title,selects=results)    

def color_extreme(val):
    if val<0:
        return 'color: {}'.format('red')
    else:
        return 'color: {}'.format('black')

def make_clickable(val):
    # print('val=',val)
    # return '<a href="sales.brh_table?={}">{}</a>'.format(val,val)
    return '<a href=brh_table/{} target="_blank"> {} </a>'.format(val,val)
                    
@sales.route("/da_table", methods=['GET', 'POST'])
@login_required
def da_table():
    df=pd.DataFrame()
    if request.method == 'POST': # submit
        checkboxs = request.form.getlist('checkboxs')
        for chk in checkboxs:
            dfT=getDataframe(chk)
            dfT=dfProc(dfT)
            df= pd.concat([df,dfT])

        df=pd.DataFrame(df.groupby(['지점그룹','지점','월'])['초회보험료'].agg('sum'))
        df['초회보험료']=round(df['초회보험료']/ 1000,0)
        # pivot
        df = pd.pivot_table(df, values='초회보험료',
                       index=['지점그룹', '지점'],
                       columns=['월'],
                       fill_value=0, aggfunc=sum, dropna=True, )
        #subtotal, grand total
        df=pd.concat([
            d.append(d.sum().rename((k, 'Total')))
            for k, d in df.groupby(level=0)
            ]).append(df.sum().rename(('Grand', 'Total')))                       
        df=df.reset_index().sort_values(by=['지점그룹','지점'],ascending=[False,True])
        print('cols=',df.columns)
        col = []  #숫자컬럼만
        for i in df.columns:
            if not i in ['지점','지점그룹']:
                col.append(i)
        print('numeric cols===', col)
        #직영구성비
        dft=df[df.지점그룹=='Grand']
        df_jik= df[(df.지점그룹=='직영') & (df.지점=='Total') ]
        for i in col:
            df_jik[i]=round(float(df_jik[i])*100/float(dft[i]),0)
        df_jik['지점']='M/S'
        df=df.append(df_jik)

        df.reset_index(drop=True,inplace=True)

        # df_with_style=df.style.format(make_clickable,subset=pd.IndexSlice[:,'지점'])
        df_with_style = df.style.format(make_clickable)
        df_with_style = df_with_style.applymap(color_extreme,subset=pd.IndexSlice[:,col])
        ## data의 format을 변경할 때 
        for i in col:
            df_with_style = df_with_style.format({i:"{:,.0f}"})
        styles = [
        {'selector':'th', 'props':[('font-size', '12px'),('text-align', 'center'),('border','1px solid #7a7')]},
        {'selector':'td', 
         'props':[('text-align', 'right'), ('font-size', '12px'), ('height', '20px'), ('width', '100px')
            ,('border','1px solid #7a7')
         ]}, 
        {'selector':'tr', 'props':[('font-size', '12px'),('text-align', 'right'),('border','1px solid #7a7')]}
        ]
        df_with_style = df_with_style.set_table_styles(styles)

        ## html로 렌더링해주어야 함 

app/app/templates/sales/bar_chart.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

<title> {{title}}</title>
{% block body %}
    <br><br><br>
    <form action="" method="post" class="form" role="form" onsumit="return false">
     <div class="content">
      <div style="text-align: right">
        {{title}}&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{{ url_for('sales.line_chart') }}" >추세 차트이동</a>
      </div>
      {% if selects %}
        &nbsp;&nbsp;&nbsp;&nbsp; 선택
        {% for item in selects %}
           {% set checked="" %}
           {% if loop.index0==0 %}
              {% set checked="checked" %}
           {% endif %}
           &nbsp;&nbsp;
           <label class="checkbox-inline">
             <input type="checkbox" class="chk" name="checkboxs" id="checkboxs" value="{{item}}" {{checked}} > {{item}}
           </label>
        {% endfor %}
     {% endif %}
     <div style="text-align: center">
      <input type="button"  class='btn btn-info' id='proc_bar' value="지점 Chart" > 
      <input type="button"  class='btn btn-info' id='proc_pie' value="직영 Chart" > 
    </div>
  </div>
  </form>
  
  <div class="container">
   <div class="row">
      <!-- bar chart canvas element -->
      <div class="col-sm-6">
      <!-- bar chart canvas element -->
      <canvas id="myChartbar" style="width:50vw; height:50vh"></canvas>
      <p id="pointSelected1">Point selected:</p>
      </div>
      <div class="col-sm-6">
      <!-- pie chart canvas element -->
        <canvas id="myChartpie" style="width:50vw; height:50vh"></canvas>
        <p id="pointSelected2">Point selected:</p>
      </div>
    </div>
  </div>
  
  <script>
  ym=''
  //bar chart view
  $('#proc_bar').click(function() {
    var arr = [];
    $('input.chk:checkbox:checked').each(function () {
        arr.push($(this).val());
    });
    ym=arr[0]; //첫번째건
    var lbl=[];  
    var dat;
    var chks;  
    $.ajax({
      type: "POST",
      data: {chkYm:arr, Types: 'bar'} ,  
      url: "{{ url_for('sales.bar_chart') }}",
      success: function(responseDt){
        full_data = JSON.parse(responseDt.resdata);
        dat = full_data['data'];
        lbl = full_data['labels'];
        chks = full_data['checks'];
      },
      async: false
    }); //end of ajax call

    var type="myChartbar"
    make_chart(dat,lbl,chks,type);
  }); //end of proc_ct
 
  //pie chart view
  $('#proc_pie').click(function() {
    var arr = [];
    $('input.chk:checkbox:checked').each(function () {
        arr.push($(this).val());
    });
    ym=arr[0]; //첫번째 ym
    var lbl=[];  
    var dat;
    var chks;  
    $.ajax({
      type: "POST",
      data: {chkYm:arr, Types: 'pie'} ,  
      url: "{{ url_for('sales.bar_chart') }}",
      success: function(responseDt){
        full_data = JSON.parse(responseDt.resdata);
        dat = full_data['data'];
        lbl = full_data['labels'];
        chks = full_data['checks'];
      },
      async: false
    }); //end of ajax call

    var ChartName="myChartpie"
    make_chart(dat,lbl,chks,ChartName);
  }); //end of proc_ct

  function make_chart(dat,lbl,chks,ChartName) {
      chart_type = ChartName.slice(-3)
      // Global parameters:
      // do not resize the chart canvas when its container does (keep at 600x400px)
      Chart.defaults.global.responsive = false;
      Chart.defaults.global.animationSteps = 50;
      Chart.defaults.global.tooltipYPadding = 16;
      Chart.defaults.global.tooltipCornerRadius = 0;
      Chart.defaults.global.tooltipTitleFontStyle = "normal";
      Chart.defaults.global.tooltipFillColor = "rgba(0,0,0,0.8)";
      Chart.defaults.global.animationEasing = "easeOutBounce";
      Chart.defaults.global.scaleLineColor = "black";
      Chart.defaults.global.scaleFontSize = 16;

      ChartData = {}; //declare an object
      ChartData.labels = []; //add 'labels' element to object (X axis)
      ChartData.datasets = []; //add 'datasets' array element to object
      cnt=dat.length;
      // alert(cnt);
      for (line = 0; line < cnt; line++) {
          if (line==0)
             ChartData.labels = lbl[line] ;  // x축 라벨

          ChartData.datasets.push({}); //create a new line dataset
          dataset = ChartData.datasets[line]
           
          dataset.fill = false;
          dataset.label= chks[line];  //데이터셋 안의 라벨
          dataset.data = []; //contains the 'Y; axis data
          dataset.data = dat[line];
          // alert(dataset.data);
      } //for line

      if (chart_type=="bar") {
        var options = { 
            scales: {
             xAxes: [{ stacked: true }],
             yAxes: [{ stacked: true ,
                   ticks: {
                      callback: function (value, index, values) {
                       return value.toLocaleString({style:"currency", currency:"won"});
                      }
                    }
                  }]
            },
            scaleOverride: false,
          // scaleSteps: steps,
          // scaleStepWidth: Math.ceil(max / steps),
          scaleStartValue: 0,
          // scaleShowVerticalLines: true,
          // scaleShowGridLines : true,
          barShowStroke : false,
          scaleShowLabels: false,
          bezierCurve: false,    
          title: {
            display: true,
            text: '지점별 실적'+' ['+ ym + ']'
          },        
          tooltips: {
            enabled: true,
            mode: 'label',
            callbacks: {
              label: function(tooltipItems, data) {
                       var label = data.datasets[tooltipItems.datasetIndex].label
                       return label + tooltipItems.yLabel.toLocaleString() + ' 천원';
              }
            }
          },
          plugins: {
            datalabels: {
              display: false,
            },
              colorschemes: {
              scheme: 'brewer.PastelOne9'
            }
          }
        };
      } //end of bar option
     
      if (chart_type=="pie") {
        var options= {
          //  pieceLabel: { 
          //   //  mode:"label", 
          //   //  render: 'value',
          //    position:"outside", 
          //    fontSize: 20, 
          //    fontColor: 'rgba(200,200,200,1)',
          //    fontStyle: 'bold'
          //  },
           title: {
            display: true,
            text: '직영실적 구성비'+' ['+ ym + ']'
           },
           tooltips: {
            mode: 'label',
            callbacks: {
                label: function(tooltipItem, data) {
                    var value = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index].toLocaleString();
                    var label = data.labels[tooltipItem.index];
                    return label + ': ' + value;
                }
            }
           },
           plugins: {
             colorschemes: {
               scheme: 'brewer.Paired12'
             },
             //각 pie의 %산출
             datalabels: {
              formatter: (value, ctx) => {
                let datasets = ctx.chart.data.datasets;
                if (datasets.indexOf(ctx.dataset) === datasets.length - 1) {
                  let sum = datasets[0].data.reduce((a, b) => a + b, 0);
                  let percentage = Math.round((value / sum) * 100) + '%';
                  return percentage;
                } else {
                  return percentage;
                }
             },
             color: '#fff',
            }
          }
        }
      } //end of pie option

      // define the chart data
      // bar chart data

     // get chart canvas
      var holder = document.getElementById(ChartName);
      var ctx = document.getElementById(ChartName).getContext("2d");
      steps = 10
      // max = {{ max }}
      max=17000
      // create the chart using the chart canvas
      var myChart = new Chart(ctx, {
        type: chart_type,
        data: ChartData,
        options: options
      });

      // get the text element below the chart
      if (chart_type=="bar") {
          var pointSelected = document.getElementById("pointSelected1");
      }
      if (chart_type=="pie") {
          var pointSelected = document.getElementById("pointSelected2");
      }

      // create a callback function for updating the selected index on the chart
      holder.onclick = function(evt){
        var activePoint = myChart.getElementAtEvent(evt);
        console.log(activePoint);
        console.log('x:' + activePoint[0]._view.x);
        console.log('maxWidth: ' + activePoint[0]._xScale.maxWidth);
        console.log('y: ' + activePoint[0]._view.y);
        console.log('index: ' + activePoint[0]._index);
        pointSelected.innerHTML = 'Point selected... index: ' + activePoint[0]._index;
      };
      function dynamicColors() {
        var r = Math.floor(Math.random() * 255);
        var g = Math.floor(Math.random() * 255);
        var b = Math.floor(Math.random() * 255);
        return "rgba(" + r + "," + g + "," + b + ", 0.5)";
      };
      function poolColors(a) {
        var pool = [];
        for(i = 0; i < a; i++) {
            pool.push(dynamicColors());
        }
        return pool;
      };
    } //end of make_chart
</script>

{% endblock %}

app/app/templates/sales/line_chart.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

<title> {{title}}</title>
{% block body %}
    <br>
    <div class="container">
      <div class="content">
        <form action="" method="post" class="form" role="form" onsumit="return false">
        <br><br>
        <div id="fixed" >
          <div style="text-align: right">
            {{title}}&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{{ url_for('sales.bar_chart') }}" >지점별 차트이동</a>
          </div>
          {% if selects %}
             &nbsp;&nbsp;&nbsp;&nbsp; 선택
          {% for item in selects %}
             {% set checked="" %}
             {% if loop.index0==0 %}
                 {% set checked="checked" %}
             {% endif %}
             &nbsp;&nbsp;
             <label class="checkbox-inline">
                 <input type="checkbox" class="chk" name="checkboxs" id="checkboxs" value="{{item}}" {{checked}}> {{item}}
             </label>
           {% endfor %}
             <br>
            <div class="row">
               &nbsp;&nbsp;&nbsp;&nbsp; type
               <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-default active">
                    <input type="radio" name="options" id="option1" autocomplete="off" value="line" checked> Line
                  </label>
                  <label class="btn btn-default">
                    <input type="radio" name="options" id="option1" autocomplete="off" value="bar"> Bar
                  </label>
                </div>
            </div>
            <div style="text-align: center">
                <input type="button"  class='btn btn-info' id='proc_ct' value="Chart View" > 
                <input type="button"  class='btn btn-info' id='proc_tb' value="Table View" > 
             </div>
            <br><br>
            {% endif %}
          </div>
        </form>

        <div class="container">
          <div class="row">
          <!-- bar chart canvas element -->
            <div class="col-sm-7">
              <canvas id="myChart" style="width:100%;"></canvas>
              <p id="pointSelected">Point selected:</p>
            </div>                   
            <div class="col-sm-5">
              <div id="results" style="height:100vh">{{ data|safe }} </div>
            </div>
          </div>
        </div>
        <script>
      
        // 차트view버튼 클릭시 web server call
        $('#proc_ct').click(function() {
     
             // 체크된 항목을 alert
          var arr = [];
          $('input.chk:checkbox:checked').each(function () {
              arr.push($(this).val());
          });
          //alert(arr);
          
          //vTtype= $('input[name="checkboxs"]:checked').val();
          var lbl=[];  
          var dat;  
          $.ajax({
            type: "POST",
            //체크된 항목만 전달
            //data:  $('.chk:checked').serialize(), 
            //data: JSON.stringify(req_data),  json으로 넘길때
            //contentType: 'application/json',
            data: {chkYm:arr, Types: 'names'} ,  
            url: "{{ url_for('sales.line_chart') }}",
            success: function(responseDt){
              full_data = JSON.parse(responseDt.resdata);
              dat = full_data['data'];
              lbl = full_data['labels'];
              chks = full_data['checks'];
             },
             async: false
          });
          
          make_chart(dat,lbl,chks);
    
          //if (myChart != undefined || myChart !=null) {
          //    alert('11');
          //    myChart.destroy();
          //}
          vTtype= $('input[name="cRatio"]:checked').val();
        });
          
        function make_chart(dat,lbl,chks) {
          var chart_type = $('input[name="options"]:checked').val();
          // Global parameters:
          // do not resize the chart canvas when its container does (keep at 600x400px)
          Chart.defaults.global.responsive = false;
        
          // define the chart data
          lineChartData = {}; //declare an object
          lineChartData.labels = []; //add 'labels' element to object (X axis)
          lineChartData.datasets = []; //add 'datasets' array element to object
          cnt=dat.length;
          for (line = 0; line < cnt; line++) {
            y = [];
            lineChartData.datasets.push({}); //create a new line dataset
            dataset = lineChartData.datasets[line]
           
            dataset.fill = false;
            dataset.label = chks[line];  //데이터셋 안의 라벨
            //dataset.strokeColor = "rgba(200,200,200,1)";
            dataset.data = []; //contains the 'Y; axis data

            if (line==0)
               lineChartData.labels = lbl[line] ;  // x축 라벨
             
            if (line== cnt-1) {
                 dataset.type = 'bar';
                 dataset.label = chks[0]+'일별';
            }
                   
            dataset.data =dat[line]  
            // lineChartData.datasets.push({
            //   labels: lbl[line],
            //   data: dat[line]
            // });
          } //for line

          // get chart canvas
          var holder = document.getElementById("myChart");
          var ctx = document.getElementById("myChart").getContext("2d");
          
          // create the chart using the chart canvas
          window.myChart = new Chart(ctx, {
              type: chart_type,
              data: lineChartData,   //x축라벨,데이터셋들(label, values)
              options: {
                scales: {
                  yAxes: [
                    { ticks: {
                       callback: function (value, index, values) {
                       return value.toLocaleString({style:"currency", currency:"won"});
                      }
                    }
                  }]
                },
                tooltips: {
                  enabled: true,
                  mode: 'single',
                  callbacks: {
                    label: function(tooltipItems, data) {
                           return tooltipItems.yLabel.toLocaleString() + ' 천원';
                    }
                  }
                },
                plugins: {
                  datalabels: {
                    display: false,
                  },
                  colorschemes: {
                  scheme: 'brewer.PastelOne3'
                  }
                }
              }
          });
              
          // get the text element below the chart
          var pointSelected = document.getElementById("pointSelected");
        
          // create a callback function for updating the selected index on the chart
          holder.onclick = function(evt) {
                var activePoint = myChart.getElementAtEvent(evt);
                // console.log(activePoint);
                // console.log('x:' + activePoint[0]._view.x);
                // console.log('maxWidth: ' + activePoint[0]._xScale.maxWidth);
                // console.log('y: ' + activePoint[0]._view.y);
                // console.log('index: ' + activePoint[0]._index);
                pointSelected.innerHTML = 'Point selected... index: ' + activePoint[0]._index;
          };
          
          return myChart;
        } //end of make_chart
        

        
        // table view 클릭시 web server call
        $('#proc_tb').click(function() {
            // 체크된 항목을 alert
            // var chks=[];
            // $('input[type="checkbox"].chk:checked').map(function() {
            //     var chk = $(this).val();
            //     chks.push({ 'checkboxs': chk });
            //     alert(chk)
            // })
          var lbl=[];  
          var dat;  
          $.ajax({
            type: "POST",
            //체크된 항목만 전달
            data:  $('.chk:checked').serialize(),   
            url: "{{ url_for('sales.da_table') }}",
            success: function(responseDt){
              $("#results").html(responseDt);
             },
             async: false
          });
        });

      </script>
      
    </div>
    </div>
{% endblock %}

app/app/templates/sales/pie_chart.html
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
<title> {{title}}</title>
{% block body %}
    <br>
    <br>
    <h3>{{ title }}</h3>

    <canvas id="chart" style="width:40vw; height:40vh"></canvas>
    <script>
      var pieData = {
        labels : [
          {% for item in labels %}
            "{{ item }}",
          {% endfor %}
        ],
        datasets : [{
          backgroundColor: [
          {% for item in colors %}
            "{{ item }}",
          {% endfor %}
        ],
          data : [
	    {% for item in values %}
              {{ item }},
            {% endfor %}]
         }
	    ]
      }

      var ctx = document.getElementById("chart").getContext("2d");
      Chart.defaults.global.responsive = false;
      steps = 10
      max = {{ max }}

      // draw pie chart
      var pieChart = new Chart(ctx, {
            type: 'pie',
            data: pieData
            // options: chartOptions
       });


    </script>
{% endblock %}